version: "3.8"
services:
  dark-killer:
    build: .
    image: dark-killer-bot:latest
    restart: unless-stopped
    environment:
      - PROVIDER=baileys
      - OWNER_NUMBER=${OWNER_NUMBER}
      - PORT=3000
      - PUBLIC_URL_BASE=${PUBLIC_URL_BASE}
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
      - ./public:/usr/src/app/public
      - ./auth:/usr/src/app/auth
